### ISSUE TITLE
About the classification performance of FLSL

### ISSUE THREAD

**Issue by sybapp** [ISL-CV/FLSL#1]
Hi, the FLSL is a really nice work, providing a new and interesting perspective of SSL. I noticed that there seems to be no performance classification in the paper. I would like to know if FLSL also has better performance in classification tasks compared to previous SSL methods.

**Comment by QingSuML** [comment]
The short answer is No.  FLSL does not have an edge in our empirical study on classification. As FLSL does not learn meaningful representation on image level and CLS token is not involved in the framework, FLSL is not well-suited for instance-level classification tasks.

We will very soon release a novel SSL method to learn representations good for both classification and dense prediction tasks. Stay tuned.
