### ISSUE TITLE
Problem with the retrained weights

### ISSUE THREAD

**Issue by Brown-Ebouky** [ISL-CV/FLSL#2]
Hi,

Thank you for your great work and open sourcing your code.
I am trying to use your pretrained weights, specifically the ViT-S/16 but it seems like it is a vit-base model.

Please can you upload the ViT-S/16 weights?

Thanks!

**Comment by QingSuML** [comment]
Hi, thank you for pointing out the issue. The url has been fixed. You should be able to download the model now.

**Comment by Brown-Ebouky** [comment]
Thank you. It works now!

**Comment by KJ-rc** [comment]
@Brown-Ebouky 
Hi, do you have a copy of the vit-base pre-trained weights?

**Comment by Brown-Ebouky** [comment]
Hi @KJ-rc ,

No, I don't have access to the vit-base weights, only the vit-small which has been released by the authors

**Comment by KJ-rc** [comment]
Hi @Brown-Ebouky ,

Thanks for the clarification. That's unfortunate. I appreciate your response.
